#!/bin/sh

# Initially from
# https://git.sr.ht/~rjarry/aerc/tree/master/item/filters/html-unsafe

# aerc filter which runs w3m using socksify (from the dante package) to prevent
# any phoning home by rendered emails. If socksify is not installed then w3m is
# used without it.
if command -v socksify >/dev/null; then
  export SOCKS_SERVER="127.0.0.1:1"
  PRE_CMD=socksify
else
  PRE_CMD=""
fi
exec $PRE_CMD w3m \
  -I "$1" \
  -T text/html \
  -cols "$(tput cols)" \
  -o display_image=false \
  -o display_link_number=true
  #-dump \
