#!/bin/sh

# Priority over PATH
[ -d "${HOME}/.local/bin" ] && export PATH="${HOME}/.local/bin:${PATH}"

# PATH has priority
[ -d "${HOME}/.yarn/bin" ] && export PATH="${PATH}:${HOME}/.yarn/bin"
[ -d "${HOME}/.cargo/bin" ] && export PATH="${PATH}:${HOME}/.cargo/bin"
[ -d "${HOME}/.local/pipx/venvs" ] && export PATH="${PATH}:${HOME}/.local/pipx/venvs"
